// SPDX-License-Identifier: MIT

pragma solidity 0.8.28;

/// @title ICoprocessorOutputs Interface
/// @notice Defines the outputs that can be generated by a coprocessor
interface ICoprocessorOutputs {
    /// @notice Emits a notice event with the given payload
    /// @param payload The ABI-encoded payload containing notice data
    function Notice(bytes calldata payload) external;

    /// @notice Issues a voucher to execute a specific action
    /// @param destination The address to which the voucher is directed
    /// @param value The amount of ETH to transfer with the voucher
    /// @param payload The ABI-encoded payload containing the action data
    function Voucher(
        address destination,
        uint256 value,
        bytes calldata payload
    ) external;
}
